name: "Hannah's Blog"
favicon: null
layout_spectrum: 0.49582
typography_spectrum: 0.50598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#77775b'
    - '#fffff3'
    - '#141108'
    - '#65a42f'
    - '#beb6a3'
  brandStrength: 1
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
