name: Simplify
favicon: null
layout_spectrum: 0.43653
typography_spectrum: 0.50598
title: A Sweetly Simple Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060412'
    - '#2c5e41'
    - '#919692'
    - '#ff587e'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
