name: "Hannah's Blog"
favicon: null
layout_spectrum: 0.49582
typography_spectrum: 0.50598
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060412'
    - '#2c5e41'
    - '#919692'
    - '#ff587e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
